/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_reeonce_myjniapplication_GlWorld */

#ifndef _Included_com_example_reeonce_myjniapplication_GlWorld
#define _Included_com_example_reeonce_myjniapplication_GlWorld
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_example_reeonce_myjniapplication_GlWorld_getMessage(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
